version: 2
updates:
  # Enable version updates for Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:30"
    open-pull-requests-limit: 5
    assignees:
      - "pyaethu-aung"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:30"
    open-pull-requests-limit: 5
    assignees:
      - "pyaethu-aung"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci(deps):"
      include: "scope"
